config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'homes/top'
  end
  get 'edit' => 'customers#edit'
  resource :customers, only: [:show, :update] do
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:new, :index, :create, :show]
  end

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    passwords: 'customers/passwords',
    sessions: 'customers/sessions'}

  root 'homes#top'
  get 'homes/about'

  namespace :admins do
    get 'searches/search'
    resources :items, only:[:index,:create, :new, :edit, :show, :update]
    resources :orders, only:[:index, :create, :show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :edit, :show, :update]
    resources :order_details, only:[:index, :create, :show, :update]
  end

  resources :items, only: [:index, :show]
  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customer_unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw', as: 'customer_withdraw'

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  
  post 'orders/confirm' => 'orders#confirm', as: 'order_confirm'
  get 'orders/complete' => 'orders#complete', as: 'order_complete'

  get 'order_details/index'

  resources :genres, only: [:index, :show] do
    resources :items, only: [:index, :show]
  end

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    sessions: 'admins/sessions'}

  get '/search', to: 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  # エラー
  validates :amount, presence: true
  # 数量0以下に変更して保存されないように
  belongs_to :customer
  belongs_to :item

  def validate_into_cart
     cart_items = self.customer.cart_items
     if (amount) == nil
        return (false)
     elsif cart_items.any? {|cart_item| cart_item.item_id == (item_id)} == true
        return (false)
     else
       return (true)
     end
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
   @cart_items = current_customer.cart_items
   @total_price = calculate(current_customer)
  end

  def update
  	cart_item = CartItem.find(params[:id])
    cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
  	cart_item = CartItem.find(params[:id])
  	cart_item.destroy
  	redirect_to cart_items_path
  end

  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end

  def create
    if current_customer
      @cart_item = current_customer.cart_items.new(cart_item_params)
      if @cart_item.save
        redirect_to cart_items_path
      else
        redirect_to items_path
      end
    else
      flash[:alert] = "※商品をカートに入れる際はログインもしくは会員登録が必要になります"
      redirect_to new_customer_session_path
    end
  end

  private
  def cart_item_params
  	params.require(:cart_item).permit(:item_id,:customer_id,:amount)
  end

  def calculate(customer)
    total_price = 0
    customer.cart_items.each do |cart_item|
      total_price += cart_item.amount * cart_item.item.price
    end
    return (total_price * 1.1).floor
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container">
    <div class="row">
      <div class="offset-1">
        <h2><span class="contents_title">ショッピングカート</span></h2>
      </div>

      <div class= "text-right">
        <%= link_to "カートを空にする", destroy_all_cart_items_path, method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
    </div>

    <div class="row">
      <div class="offset-1 col-9">
        <table class="table">
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
              <th colspan="1"></th>
            </tr>
          </thead>

          <% @cart_items.each do |cart_item| %>
            <tbody>
              <tr>
                <td class="align-middle">
                  <%= attachment_image_tag cart_item.item, :image, size: "50x50", fallback: "img/no-image.png" %>
                  <span><%= cart_item.item.name %></span>
                </td>
                <td class="align-middle"><%= (cart_item.item.price * 1.1).floor %></td>
                <td class="align-middle" style="width: 130px;">
                  <%= form_for(cart_item) do |f| %>
                  <div class="row">
                    <%= f.number_field :amount, min:1,class: "col-6" %>
                    <%= f.submit "変更", class: "btn btn-sm btn-outline-danger offset-1 col-4" %>
                  </div>
                  <% end %>
                </td>

                <td>
                  <%= (cart_item.item.price * 1.1).floor * cart_item.amount %>
                </td>

                <td><%= link_to "削除する", cart_item_path(cart_item), method: :delete, class: "btn btn-sm btn-danger" %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>

      <div class="row my-3">
        <div class="offset-9 text-right">
          <strong>合計金額 <%= @total_price %>円</strong>
        </div>
      </div>

    <div class="row">
      <div class="offset-1 col-2">
        <%= link_to "買い物を続ける", root_path, class: "btn btn-primary" %>
      </div>
      
      <div class="offset-6 text-center">
        <%= link_to "情報入力に進む", new_customers_order_path, class: "btn btn-success" %>
      
      </div>
    </div>
</div>