config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'homes/top'
  end
  get 'edit' => 'customers#edit'
  resource :customers, only: [:show, :update] do
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:new, :index, :create, :show]
  end

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    passwords: 'customers/passwords',
    sessions: 'customers/sessions'}

  root 'homes#top'
  get 'homes/about'

  namespace :admins do
    get 'searches/search'
    resources :items, only:[:index,:create, :new, :edit, :show, :update]
    resources :orders, only:[:index, :create, :show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :edit, :show, :update]
    resources :order_details, only:[:index, :create, :show, :update]
  end

  resources :items, only: [:index, :show]
  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customer_unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw', as: 'customer_withdraw'

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  
  post 'orders/confirm' => 'orders#confirm', as: 'order_confirm'
  get 'orders/complete' => 'orders#complete', as: 'order_complete'

  get 'order_details/index'

  resources :genres, only: [:index, :show] do
    resources :items, only: [:index, :show]
  end

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    sessions: 'admins/sessions'}

  get '/search', to: 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
	belongs_to :genre
	attachment :image
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  def edit
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      redirect_to new_admins_item_path
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item)
    else
      redirect_to edit_admins_item_path(@item)
    end
  end

  private
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@genres = Genre.where(is_active: true)# ジャンルが有効のみ
  	# もしURLに[:genre_id]が含まれていたら
    if params[:genre_id]
      # その[:genre_id]のデータをGenreから@genreに格納
      @genre = Genre.find(params[:genre_id])
      # @genreに紐付いた商品で販売可の商品を引っ張る（作成順の昇順）
      @items = @genre.items.order(created_at: :desc).where(is_active: "販売中").page(params[:page]).per(8)
      # 含まれていなければ
    else
      @items = Item.where(is_active: "販売中").page(params[:page]).per(8)
     # 販売ステータスが販売可のみの商品を参照 ジャンル作成の昇順
    end
  end

  def show
    @item = Item.find(params[:id])
  	@cart_item = @item.cart_items.build
    @genres = Genre.where(is_active: true)# ジャンルが有効のみ
  end
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_genrebox.html.erb
<div class="col-sm-2">
	<div class="panel panel-default">
		<div class="panel-heading text-center">
			<h3 class="panel-title">ジャンル検索</h3>
		</div>
		<div class="panel-body">
		<%= link_to "すべての商品", items_path %>
		</div>
		<% genres.each do |genre| %>
		<div class="panel-body">
			<%= link_to genre.name, genre_items_path(genre) %>
		</div>
		<% end %>
	</div>
</div>

app/views/items/_index.html.erb
<div class="col-sm-9">
	<div class="page-header m-0">
	<h2>
		<% if params[:genre_id] %>
            <%= @genre.name %>一覧
          <% else %>
            商品一覧
          <% end %> </h2>
</div>

<div class="container">
	<div class="col-sm-9">
	<% items.each do |item| %>
		<div class="col-xs-3 mt-3"> <!--ひとつのブロックをラップしてカラムを指定する-->
			<%= link_to item_path(item) do %><!--それをeach文で回す-->
			<%= attachment_image_tag item, :image, size: "150x150", format: 'jpeg', fallback: "no_image.jpg", class: 'rounded' %>
			<% end %>
			<br>
			<strong class="red-border"><%= link_to item.name, item_path(item) %></strong>
			<br>
			<span class="ml-auto">¥<%= (item.price * 1.1).floor %></span><br>
		</div>
	<% end %>
</div>
</div>
<!-- items#indexのコメントを参考に、ジャンルごとの商品の情報を持ってくる -->

app/views/items/index.html.erb
		<!-- genres/indexから　トップページ、商品一覧、商品詳細で呼び出す予定 -->
		<%= render 'genrebox', genres: @genres %>
		<!-- genres/indexから　トップページ、商品一覧、商品詳細で呼び出す予定 -->
<div class="col-sm-9">
	<div class="page-header m-0">
	<h2>
		<% if params[:genre_id] %>
            <%= @genre.name %>一覧
          <% else %>
            商品一覧
          <% end %> <small>(全<%= @items.count %>件)</small></h2>
</div>

<div class="container">
	<div class="col-sm-9">
	<% @items.each do |item| %>
		<div class="col-xs-3 mt-3"> <!--ひとつのブロックをラップしてカラムを指定する-->
			<%= link_to item_path(item) do %><!--それをeach文で回す-->
			<%= attachment_image_tag item, :image, size: "150x150", format: 'jpeg', fallback: "no_image.jpg", class: 'rounded' %>
			<% end %>
			<br>
			<strong class="red-border"><%= link_to item.name, item_path(item) %></strong>
			<br>
			<span class="ml-auto">¥<%= (item.price * 1.1).floor %></span><br>
		</div>
	<% end %>
</div>
</div>
<!-- items#indexのコメントを参考に、ジャンルごとの商品の情報を持ってくる -->

app/views/items/show.html.erb
<%= render 'genrebox', genres: @genres %>

<div class="col-sm-9">
	<%= link_to item_path(@item) do %>
		<%= attachment_image_tag @item, :image, size: "300x300", format: 'jpeg', fallback: "no_image.jpg", class: 'rounded' %>
	<% end %>
	<br>
	<h2><strong class="red-border"><%= @item.name %></strong></h2>
	<h4><%= @item.introduction %></h4>
	<h3><span class="ml-auto">¥<%= (@item.price * 1.1).floor %> (税込)</span><br></h3>
	<%= form_for(@cart_item, url: cart_items_path) do |f|  %>
	    <%= f.select :amount, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]], include_blank: "個数選択" %>
			<%= f.hidden_field :item_id, :value => @item.id %>
		<%= f.submit 'カートに入れる'%>
  	<% end %>
</div>