config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'homes/top'
  end
  get 'edit' => 'customers#edit'
  resource :customers, only: [:show, :update] do
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:new, :index, :create, :show]
  end

  devise_for :customers, controllers: {
    registrations: 'customers/registrations',
    passwords: 'customers/passwords',
    sessions: 'customers/sessions'}

  root 'homes#top'
  get 'homes/about'

  namespace :admins do
    get 'searches/search'
    resources :items, only:[:index,:create, :new, :edit, :show, :update]
    resources :orders, only:[:index, :create, :show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :edit, :show, :update]
    resources :order_details, only:[:index, :create, :show, :update]
  end

  resources :items, only: [:index, :show]
  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customer_unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw', as: 'customer_withdraw'

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  
  post 'orders/confirm' => 'orders#confirm', as: 'order_confirm'
  get 'orders/complete' => 'orders#complete', as: 'order_complete'

  get 'order_details/index'

  resources :genres, only: [:index, :show] do
    resources :items, only: [:index, :show]
  end

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    sessions: 'admins/sessions'}

  get '/search', to: 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	enum payment: {creditcard: 0, transfer: 1}

	enum status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

	has_many :order_details, dependent: :destroy
	#中間テーブルを介して複数のプロダクトを持つ
	has_many :items, :through => :order_items
	#オーダーアイテムを複数追加するためのメソッド
	#accepts_nested_attributes_for :order_items

	validates :address, presence: true,
	length: {maximum: 35, minimum: 2}
	validates :postal_code, presence: true,
	length: {maximum: 10, minimum: 2}

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController

  before_action :authenticate_admin!
  def index
    if params[:id] # 会員詳細から来た場合
      @orders = Customer.find(params[:id]).orders.page(params[:page]).per(10)
    elsif params[:flag] == "top" # TOP本日受注分から来た場合
      @orders = Order.where(created_at:  Time.zone.now.all_day).page(params[:page]).per(10)
    else
      @orders = Order.page(params[:page]).per(10)
    end
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @orders = Order.all
    order_details = @order.order_details
    @order.update(order_params)
    # 注文ステータス[入金確認]=>制作ステータス[製作待ち]
    if @order.status == "入金確認"
      @order.order_details.each do |order_item|
        order_item.update(making_status: "製作待ち")
      end
    end
    flash[:notice] = "You have updated status successfully."
    redirect_to admins_order_path(@order.id)
  end


  private

  def order_params
    params.require(:order).permit(:status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:making_status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @address = Address.where(customer_id:current_customer.id)
    @my_address = Customer.find(current_customer.id)
    @order = Order.new
    @addresses = current_customer.addresses
  end

  def confirm
    @order = Order.new(order_params)
    if params[:order][:address] == "1"
      @my_address = Customer.find(current_customer.id)
      @order.postal_code = @my_address.postal_code
      @order.address = @my_address.address
      order_last_name = @my_address.last_name
      order_first_name = @my_address.first_name
      @order.name = order_last_name + order_first_name
    elsif params[:order][:address] == "2"
      @address = Address.find(params[:order][:id])
      @order.name = @address.name
      @order.address = @address.delivery
      @order.postal_code = @address.postal_code
    elsif params[:order][:address] == "3"
      @order.name = params[:order][:new_address][:name]
      @order.address = params[:order][:new_address][:delivery]
      @order.postal_code = params[:order][:new_address][:postal_code]
    end
    @new = params[:order][:new_address][:postal_code]
    @order.total_price = calculate(current_customer)
    
  end





  def complete
  end

  def create
    @order = Order.new(order_params)
    @order.save
    current_customer.cart_items.each do |cart_item|
      @order_detail = OrderDetail.new
      @order_detail.item_id = cart_item.item_id
      @order_detail.order_id = @order.id
      @order_detail.amount = cart_item.amount
      @order_detail.making_status = 0
      @order_detail.price = (cart_item.item.price * cart_item.amount * 1.1).floor
      @order_detail.save
    end
    #address = current_customer.addresses.new
    #address.name = @order.name
    #address.delivery = @order.address
    #address.postal_code = @order.postal_code
    #address.save

    address = current_customer.addresses.new(name: @order.name, delivery: @order.address, postal_code: @order.postal_code)
    unless current_customer.address_posted?(address)
      address.save
    end

    current_customer.cart_items.delete_all
    redirect_to order_complete_path
  end

  def index
    @orders = Customer.find(current_customer.id).orders.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end


  private

  def order_params
    params.require(:order).permit(:customer_id, :total_price, :shipping_cost, :payment, :status, :postal_code, :address, :name)
  end

  def calculate(customer)
    total_price = 0
    customer.cart_items.each do |cart_item|
      total_price += cart_item.amount * cart_item.item.price
    end
    return (total_price * 1.1).floor
  end

end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/orders/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h2><span class="contents_title">注文履歴一覧</span></h2>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-sm-10 col-sm-offset-1">
      <table class="table table-hover">
        <thead class="contents_title">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M"), admins_order_path(order) %></td>
              <!-- .strftime => created_atの表記を設定 -->
              <td><%= order.customer.last_name %>
                <%= order.customer.first_name %>
              </td>
              <td><%= order.order_details.sum(:amount) %></td>
              <td><%= order.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
 </div>

   <!-- ページネーション -->


  <div class="container">
    <div class="row">
     <div class="col-md-4 offset-md-4 py-2  mt-5">
      <%= paginate @orders %>
     </div>
    </div>
  </div>

app/views/admins/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="customer_head">
      <h2><span class="contents_title">注文履歴詳細</span></h2>
    </div>
  </div>

  <div class="order_customer">
  	<table>
      <tr valign="top">
        <th class="col-xs-2 postal_code">購入者</th>
        <td class="col-xs-10 ">
        <%= link_to ("#{@order.customer.last_name} #{@order.customer.first_name}"), admins_customer_path(@order.customer) %>
        </td>
      </tr>
      <div>
      <tr valign="top">
        <th class="col-xs-2  postal_code_delivary">配送先</th>
        <td class="col-xs-10">〒<%= @order.postal_code %><%= @order.address %><br>
        	<%= @order.name %></td>
      </tr>
      <tr valign="top">
        <th class="col-xs-2 postal_code">支払方法</th>
        <td class="col-xs-10"><%= @order.payment_i18n %></td>
      </tr>
      <tr valign="top">
        <th class="col-xs-2 postal_code">注文ステータス</th>
        <td class="col-xs-10">
            <%= form_for (@order), url: admins_order_path(@order) do |f| %>
            <%= f.select :status, [["入金待ち", "入金待ち"], ["入金確認","入金確認"],["製作中","製作中"],["発送準備中","発送準備中"],["発送済み","発送済み"]], class: "form-control" %>
            <%= f.submit "更新", class: "btn btn-primary btn-sm" %>
            <% end %>
        </td>
      </tr>
    </table>
  </div>

  <div class="row">
    <div class="col align-self-start">
    <div class="col-xs-7">
      <table class ="table">
    		<thead class="contents_title">
    			<tr>
    				<th>商品名</th>
    				<th>単価（税込）</th>
    				<th>数量</th>
    				<th>小計</th>
    				<th>製作ステータス</th>
    			</tr>
    		</thead>
    		<tbody>
          <% @order_details.each do |order|%>
          <tr>
            <th><%= order.item.name %></th>
            <th><%= (order.item.price * 1.1).floor %></th>
            <th><%= order.amount %></th>
            <th><%= ((order.item.price * order.amount) * 1.1).floor %></th>
            <th>
              <div class="row">
                <div class="col-sm-3">
                  <%= form_for (order), url: admins_order_detail_path(order) do |f| %>
                  <%= f.select :making_status, [["製作不可", "製作不可"], ["製作待ち","製作待ち"],["製作中","製作中"],["製作完了","製作完了"]], class: "form-control" %>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                  <%= f.submit "更新", class: "btn btn-primary btn-sm" %>
                </div>
                  <% end %>
              </div>
            </th>
          </tr>
          <% end %>
    		</tbody>
    	</table>
    </div>
    </div>
    <div class="col align-self-end">
      <div class="col-xs-4 col-xs-offset-1">
        <% @order_details.each do |order|%>
        <br>
        <br>
        <% end %>
      <div class="order_customer">
        <table class="col-xs-9">
            <tr>
              <th class="col-xs-7">商品合計</th>
              <td class="col-xs-5 text-right"><%= @order.total_price %>円</td>
            </tr>
            <tr>
              <th class="col-xs-7">送料</th>
              <td class="col-xs-5 text-right">800円</td>
            </tr>
            <tr>
              <th class="col-xs-7">請求金額合計</th>
              <td class="col-xs-5 text-right"><%= @order.total_price + 800 %>円</td>
            </tr>
        </table>
      </div>
      </div>
  </div>
</div>